service: mtgdb-api

provider:
  name: aws
  runtime: nodejs6.10 # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 30 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: cards # path will be domain.name.com/dev/cards
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: cards/{id} # path will be domain.name.com/dev/cards/1
          method: get
          cors: true
  getAll:
    handler: handler.getAll # path will be domain.name.com/dev/cards
    events:
     - http:
         path: cards
         method: get
         cors: true
  update:
    handler: handler.update # path will be domain.name.com/dev/cards/1
    events:
     - http:
         path: cards/{id}
         method: put
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: cards/{id} # path will be domain.name.com/dev/cards/1
         method: delete
         cors: true
  populate:
    handler: handler.populate
    events:
     - http:
         path: populate/{set}
         method: get
         cors: true
  getDBCards:
    handler: handler.getDBCards
    events:
     - http:
         path: dbCards
         method: get
         cors: true
plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation